import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fa'; // 'fa' for Dari/Persian

interface LanguageContextType {
    language: Language;
    t: (key: string) => string;
    setLanguage: (lang: Language) => void;
    isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        // Navigation
        'nav.dashboard': 'Dashboard',
        'nav.invoices': 'Invoices',
        'nav.clients': 'Clients',
        'nav.products': 'Products',
        'nav.payments': 'Payments',
        'nav.expenses': 'Expenses',
        'nav.reports': 'Reports',
        'nav.settings': 'Settings',
        'nav.backup': 'Backup',
        'nav.conflicts': 'Conflicts',
        'nav.users': 'Users',
        'nav.trash': 'Trash',

        // Common
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.add': 'Add',
        'common.create': 'Create',
        'common.search': 'Search',
        'common.searchPlaceholder': 'Search...',
        'common.filter': 'Filter',
        'common.export': 'Export',
        'common.import': 'Import',
        'common.actions': 'Actions',
        'common.status': 'Status',
        'common.date': 'Date',
        'common.amount': 'Amount',
        'common.total': 'Total',
        'common.name': 'Name',
        'common.email': 'Email',
        'common.phone': 'Phone',
        'common.address': 'Address',
        'common.notes': 'Notes',
        'common.description': 'Description',
        'common.loading': 'Loading...',
        'common.loadingApp': 'Loading Invoice Manager...',
        'common.profileError': 'Something went wrong loading your profile.',
        'common.retry': 'Retry',
        'common.noData': 'No data found',
        'common.confirm': 'Confirm',
        'common.confirmDelete': 'Confirm Delete?',
        'common.required': 'Required',
        'common.optional': 'Optional',
        'common.noTax': 'No tax',
        'common.trackStock': 'Track stock',
        'common.forProfitTracking': 'For profit tracking',

        // Auth
        'auth.appName': 'Invoice Manager',
        'auth.signInTitle': 'Sign in to your account',
        'auth.password': 'Password',
        'auth.forgotPassword': 'Forgot password?',
        'auth.signIn': 'Sign In',
        'auth.signingIn': 'Signing in...',
        'auth.noAccount': 'Don\'t have an account?',
        'auth.createAccount': 'Create one',
        'auth.enterEmailFirst': 'Please enter your email address first',
        'auth.createAccountTitle': 'Create your account',
        'auth.confirmPassword': 'Confirm Password',
        'auth.createAccountAction': 'Create Account',
        'auth.creatingAccount': 'Creating account...',
        'auth.motherAccountInfo': 'By registering, you\'ll become the mother account for your company. You can invite child users after setup.',
        'auth.alreadyHaveAccount': 'Already have an account?',
        'auth.signInLink': 'Sign in',
        'auth.companyNamePlaceholder': 'My Company',
        'auth.passwordsDoNotMatch': 'Passwords do not match',
        'auth.createAccountFailed': 'Failed to create account',
        'auth.companyNameRequired': 'Company name is required',
        'auth.passwordLength': 'Password must be at least 6 characters',
        'auth.confirmPasswordRequired': 'Please confirm your password',
        'auth.emailPlaceholder': 'email@example.com',
        'auth.passwordPlaceholder': '••••••••',

        // Dashboard
        'dashboard.title': 'Dashboard',
        'dashboard.subtitle': 'Welcome back! Here\'s your business overview.',
        'dashboard.revenueThisMonth': 'Revenue This Month',
        'dashboard.lastMonth': 'Last month',
        'dashboard.outstanding': 'Outstanding',
        'dashboard.overdue': 'Overdue',
        'dashboard.netProfit': 'Net Profit (YTD)',
        'dashboard.revenueOverview': 'Revenue Overview',
        'dashboard.invoiceStatus': 'Invoice Status',
        'dashboard.topClients': 'Top Clients',
        'dashboard.recentActivity': 'Recent Activity',
        'dashboard.noDataYet': 'No data yet',
        'dashboard.noRecentActivity': 'No recent activity',

        // Invoices
        'invoices.title': 'Invoices',
        'invoices.subtitle': 'Manage your invoices',
        'invoices.new': 'New Invoice',
        'invoices.all': 'All',
        'invoices.allStatus': 'All Status',
        'invoices.draft': 'Draft',
        'invoices.sent': 'Sent',
        'invoices.paid': 'Paid',
        'invoices.partial': 'Partial',
        'invoices.overdue': 'Overdue',
        'invoices.void': 'Void',
        'invoices.dueDate': 'Due Date',
        'invoices.viewEdit': 'View/Edit',
        'invoices.exportPdf': 'Export PDF',
        'invoices.sendEmail': 'Send Email',
        'invoices.duplicate': 'Duplicate',
        'invoices.markAsPaid': 'Mark as Paid',

        // Clients
        'clients.title': 'Clients',
        'clients.subtitle': 'Manage your clients and contacts',
        'clients.addClient': 'Add Client',
        'clients.editClient': 'Edit Client',
        'clients.billingAddress': 'Billing Address',
        'clients.shippingAddress': 'Shipping Address',
        'clients.taxNumber': 'Tax Number',

        // Products
        'products.title': 'Products',
        'products.subtitle': 'Manage your products and services',
        'products.addProduct': 'Add Product',
        'products.editProduct': 'Edit Product',
        'products.sku': 'SKU',
        'products.unit': 'Unit',
        'products.price': 'Price',
        'products.cost': 'Cost',
        'products.stock': 'Stock',
        'products.trackStock': 'Track Stock',

        // Product Units
        'units.pcs': 'pcs',
        'units.hour': 'hour',
        'units.hrs': 'hours',
        'units.day': 'day',
        'units.days': 'days',
        'units.service': 'service',
        'units.kg': 'kg',
        'units.m': 'm',
        'units.units': 'units',
        'units.items': 'items',

        // Payments
        'payments.title': 'Payments',
        'payments.subtitle': 'Track payments and refunds',
        'payments.recordPayment': 'Record Payment',
        'payments.payInFull': 'Pay in Full',
        'payments.method': 'Method',
        'payments.reference': 'Reference',
        'payments.referencePlaceholder': 'Transaction ID, check number, etc.',
        'payments.isRefund': 'This is a refund',
        'payments.selectInvoice': 'Select invoice',
        'payments.savePayment': 'Save Payment',
        'payments.cash': 'Cash',
        'payments.bankTransfer': 'Bank Transfer',
        'payments.card': 'Card',
        'payments.check': 'Check',
        'payments.other': 'Other',
        'payments.due': 'due',

        // Expenses
        'expenses.title': 'Expenses',
        'expenses.subtitle': 'Track your business expenses',
        'expenses.addExpense': 'Add Expense',
        'expenses.editExpense': 'Edit Expense',
        'expenses.category': 'Category',
        'expenses.vendor': 'Vendor',

        // Expense Categories
        'expenses.cat.officeSupplies': 'Office Supplies',
        'expenses.cat.travel': 'Travel',
        'expenses.cat.utilities': 'Utilities',
        'expenses.cat.marketing': 'Marketing',
        'expenses.cat.other': 'Other',

        // Reports
        'reports.title': 'Reports',
        'reports.subtitle': 'Analyze your business performance',
        'reports.sales': 'Sales',
        'reports.tax': 'Tax',
        'reports.profit': 'Profit',
        'reports.exportCsv': 'Export CSV',
        'reports.exportPdf': 'Export PDF',

        // Settings
        'settings.title': 'Settings',
        'settings.subtitle': 'Configure your business preferences',
        'settings.saveSuccess': 'Settings saved successfully',
        'settings.confirmSave': 'Confirm Save',
        'settings.confirmSaveMessage': 'Are you sure you want to save these changes?',
        'settings.companyInfo': 'Company Information',

        // Tutorial
        'tutorial.welcome.title': 'Welcome to Invoice Manager',
        'tutorial.welcome.desc': 'Let\'s take a quick tour to help you get started.',
        'tutorial.dashboard.title': 'Dashboard',
        'tutorial.dashboard.desc': 'View your business overview, revenue charts, and recent activity here.',
        'tutorial.invoices.title': 'Invoices',
        'tutorial.invoices.desc': 'Create, manage, and print invoices for your clients.',
        'tutorial.clients.title': 'Clients',
        'tutorial.clients.desc': 'Manage your client database and view their history.',
        'tutorial.products.title': 'Products',
        'tutorial.products.desc': 'Track your inventory, services, and prices.',
        'tutorial.payments.title': 'Payments',
        'tutorial.payments.desc': 'Record payments and track outstanding balances.',
        'tutorial.expenses.title': 'Expenses',
        'tutorial.expenses.desc': 'Log business expenses and categorize them.',
        'tutorial.reports.title': 'Reports',
        'tutorial.reports.desc': 'View detailed financial reports and analytics.',
        'tutorial.settings.title': 'Settings',
        'tutorial.settings.desc': 'Configure your company details, logo, and tax rates.',
        'tutorial.backup.title': 'Backup',
        'tutorial.backup.desc': 'Secure your data by creating and restoring backups.',
        'tutorial.trash.title': 'Trash',
        'tutorial.trash.desc': 'Recover deleted items or permanently remove them.',
        'tutorial.conflicts.title': 'Sync Conflicts',
        'tutorial.conflicts.desc': 'Resolve data conflicts between local and cloud storage.',
        'tutorial.users.title': 'User Management',
        'tutorial.users.desc': 'Invite and manage team members for your organization.',
        'tutorial.sync.title': 'Cloud Sync',
        'tutorial.sync.desc': 'Keep your data synchronized across all devices.',
        'tutorial.next': 'Next',

        'tutorial.prev': 'Previous',
        'tutorial.done': 'Done',
        'settings.restartTutorial': 'Restart Tutorial',
        'settings.companyName': 'Company Name',
        'settings.companyLogo': 'Company Logo',
        'settings.noLogo': 'No logo',
        'settings.chooseLogo': 'Choose Logo',
        'settings.companyAddress': 'Address',
        'settings.companyEmail': 'Email',
        'settings.companyPhone': 'Phone',
        'settings.taxId': 'Tax ID',
        'settings.taxIdHint': 'VAT/GST number',
        'settings.invoiceSettings': 'Invoice Settings',
        'settings.invoicePrefix': 'Invoice Prefix',
        'settings.nextNumber': 'Next Number',
        'settings.currency': 'Currency',
        'settings.currencySymbol': 'Currency Symbol',
        'settings.pdfTemplate': 'PDF Template',
        'settings.paperSize': 'Paper Size',
        'settings.defaultTerms': 'Default Terms',
        'settings.termsPlaceholder': 'Payment terms...',
        'settings.defaultNotes': 'Default Notes',
        'settings.notesPlaceholder': 'Thank you message...',
        'settings.footerText': 'Footer Text',
        'settings.footerPlaceholder': 'Invoice footer text',
        'settings.taxRates': 'Tax Rates',
        'settings.taxName': 'Tax name',
        'settings.security': 'Security',
        'settings.autoLock': 'Auto-lock after (minutes)',
        'settings.autoLockHint': 'Set to 0 to disable auto-lock',
        'settings.appearance': 'Appearance',
        'settings.theme': 'Theme',
        'settings.language': 'Language',
        'settings.dark': 'Dark',
        'settings.light': 'Light',
        'settings.system': 'System',
        'settings.saveSettings': 'Save Settings',
        'settings.saving': 'Saving...',

        // Table Headers
        'table.name': 'Name',
        'table.email': 'Email',
        'table.phone': 'Phone',
        'table.address': 'Address',
        'table.actions': 'Actions',
        'table.date': 'Date',
        'table.invoice': 'Invoice',
        'table.client': 'Client',
        'table.amount': 'Amount',
        'table.status': 'Status',
        'table.method': 'Method',
        'table.type': 'Type',
        'table.category': 'Category',
        'table.vendor': 'Vendor',
        'table.description': 'Description',
        'table.sku': 'SKU',
        'table.unit': 'Unit',
        'table.price': 'Price',
        'table.stock': 'Stock',
        'table.paid': 'Paid',
        'table.total': 'Total',
        'table.balance': 'Balance',
        'table.taxRate': 'Tax Rate',
        'table.baseAmount': 'Base Amount',
        'table.taxCollected': 'Tax Collected',

        // Reports Specific
        'reports.from': 'From:',
        'reports.to': 'To:',
        'reports.invoicesCount': 'Invoices',
        'reports.totalBilled': 'Total Billed',
        'reports.collected': 'Collected',
        'reports.taxTotal': 'Tax',
        'reports.taxableAmount': 'Taxable Amount',
        'reports.taxCollected': 'Tax Collected',
        'reports.revenue': 'Revenue',
        'reports.cogs': 'Cost of Goods',
        'reports.grossProfit': 'Gross Profit',
        'reports.netProfit': 'Net Profit',
        'reports.expensesCount': 'Expenses',
        'reports.totalSpent': 'Total Spent',
        'reports.byCategory': 'By Category',
        'reports.transactions': 'Transactions',
        'reports.received': 'Received',
        'reports.refunded': 'Refunded',

        // Empty States
        'empty.noInvoices': 'No invoices yet',
        'empty.createFirstInvoice': 'Create your first invoice to get started',
        'empty.noClients': 'No clients yet',
        'empty.addFirstClient': 'Add your first client to get started',
        'empty.noProducts': 'No products yet',
        'empty.addFirstProduct': 'Add your first product to get started',
        'empty.noPayments': 'No payments yet',
        'empty.recordFirstPayment': 'Record your first payment',
        'empty.noExpenses': 'No expenses yet',
        'empty.addFirstExpense': 'Start tracking your expenses',

        // Trash
        'trash.title': 'Trash',
        'trash.subtitle': 'Deleted items can be restored or permanently deleted',
        'trash.empty': 'Trash is empty',
        'trash.emptyDesc': 'No deleted items in this category',
        'trash.deletedAt': 'Deleted',
        'trash.warning': 'Warning',
        'trash.warningDesc': 'Permanently deleted items cannot be recovered. Restored items will be returned to their original location.',
        'trash.restore': 'Restore',
        'trash.permanentDelete': 'Delete Forever',
        'trash.confirm': 'Confirm',
        'trash.cancel': 'Cancel',

        // Status Labels
        'status.paid': 'Paid',
        'status.unpaid': 'Unpaid',
        'status.overdue': 'Overdue',
        'status.draft': 'Draft',
        'status.sent': 'Sent',
        'status.void': 'Void',
        'status.payment': 'Payment',
        'status.refund': 'Refund',

        // Activity Messages
        'activity.createdInvoice': 'Created invoice',
        'activity.deletedInvoice': 'Deleted invoice',
        'activity.updatedInvoice': 'Updated invoice',
        'activity.createdClient': 'Created client',
        'activity.createdProduct': 'Created product',
        'activity.paymentFor': 'Payment of {amount} for invoice {invoice}',

        // Backup
        'backup.title': 'Backup & Data',
        'backup.subtitle': 'Backup, restore, and manage your data',
        'backup.backupRestore': 'Backup & Restore',
        'backup.backupDesc': 'Create encrypted backups of all your data including invoices, clients, products, payments, and settings.',
        'backup.encryptionPassword': 'Encryption password (optional)',
        'backup.createBackup': 'Create Backup',
        'backup.restoreBackup': 'Restore Backup',
        'backup.importData': 'Import Data',
        'backup.importDesc': 'Import clients and products from CSV files. Expected format for clients: Name, Email, Phone, Address. For products: SKU, Name, Unit, Price, Cost.',
        'backup.importClients': 'Import Clients',
        'backup.importProducts': 'Import Products',
        'backup.exportData': 'Export Data',
        'backup.exportDesc': 'Export your data as CSV files for use in spreadsheets or other applications.',
        'backup.databaseLocation': 'Database Location',
        'backup.databaseDesc': 'Your data is stored locally at:',

        // Form Fields
        'form.billingAddress': 'Billing Address',
        'form.shippingAddress': 'Shipping Address',
        'form.taxNumber': 'Tax Number',
        'form.category': 'Category',
        'form.vendor': 'Vendor',
        'form.vendorPlaceholder': 'Vendor name',
        'form.whatExpenseFor': 'What was this expense for?',
        'form.tax': 'Tax',
        'form.update': 'Update',

        // Messages
        'msg.saved': 'Saved successfully',
        'msg.deleted': 'Deleted successfully',
        'msg.created': 'Created successfully',
        'msg.updated': 'Updated successfully',
        'msg.error': 'An error occurred',

        // Cloud Sync
        'sync.title': 'Cloud Sync',
        'sync.allSynced': 'All data synced',
        'sync.changesPending': 'Changes pending sync',
        'sync.syncing': 'Syncing...',
        'sync.neverSynced': 'Never synced',
        'sync.syncNow': 'Sync Now',
        'sync.autoSync': 'Auto-sync',
        'sync.autoSyncDescription': 'Automatically sync every 30 minutes',
        'sync.dataInfo': 'Your data is synced to Firebase and accessible from any device',
        'sync.reminderInfo': 'You\'ll be reminded to sync before closing if there are unsaved changes',

        // Users Management
        'users.title': 'Manage Users',
        'users.subtitle': 'Invite and manage child users for your organization',
        'users.addUser': 'Add User',
        'users.totalUsers': 'Total Users',
        'users.admins': 'Admins',
        'users.childUsers': 'Child Users',
        'users.user': 'User',
        'users.email': 'Email',
        'users.role': 'Role',
        'users.status': 'Status',
        'users.actions': 'Actions',
        'users.active': 'Active',
        'users.admin': 'Admin',
        'users.noUsers': 'No users yet. Click "Add User" to invite someone.',
        'users.createChildUser': 'Create Child User',
        'users.userNamePlaceholder': 'User name',
        'users.userPassword': 'User Password',
        'users.minChars': 'Minimum 6 characters',
        'users.adminPassword': 'Your Password (Admin)',
        'users.adminPasswordPlaceholder': 'Enter your password to confirm',
        'users.reauthNote': 'Required to re-authenticate after creating user',
        'users.addUserNote': 'This user will be added to your organization and can access shared data.',
        'users.creating': 'Creating...',
        'users.createUser': 'Create User',

        // Conflicts
        'conflicts.title': 'Sync Conflicts',
        'conflicts.subtitle': 'Review and resolve differences between local and cloud data',
        'conflicts.checkConflicts': 'Check for Conflicts',
        'conflicts.pending': 'Pending Conflicts',
        'conflicts.resolvedToday': 'Resolved Today',
        'conflicts.entityTypes': 'Entity Types',
        'conflicts.noConflicts': 'No Conflicts Found',
        'conflicts.inSync': 'Your local and cloud data are in sync!',
        'conflicts.checking': 'Checking for conflicts...',
        'conflicts.keepLocal': 'Keep Local',
        'conflicts.keepRemote': 'Keep Remote',
        'conflicts.localVersion': 'Local Version',
        'conflicts.remoteVersion': 'Remote Version',
        'conflicts.recentlyResolved': 'Recently Resolved',

        // Invoice Editor
        'invoice.new': 'New Invoice',
        'invoice.save': 'Save Invoice',
        'invoice.client': 'Client',
        'invoice.newClient': 'New Client',
        'invoice.selectClient': 'Select a client',
        'invoice.items': 'Items',
        'invoice.addItem': 'Add Item',
        'invoice.description': 'Description',
        'invoice.quickSelect': 'Quick select product...',
        'invoice.itemDescription': 'Item description *',
        'invoice.qty': 'Qty',
        'invoice.unitPrice': 'Unit Price',
        'invoice.taxPercent': 'Tax %',
        'invoice.discPercent': 'Disc %',
        'invoice.total': 'Total',
        'invoice.notes': 'Notes',
        'invoice.additionalNotes': 'Additional notes...',
        'invoice.terms': 'Terms',
        'invoice.termsConditions': 'Terms and conditions...',
        'invoice.issueDate': 'Issue Date',
        'invoice.dueDate': 'Due Date',
        'invoice.summary': 'Summary',
        'invoice.subtotal': 'Subtotal',
        'invoice.tax': 'Tax',

        // Audit Messages
        'audit.restoredClient': 'Restored client',
        'audit.movedClientToTrash': 'Moved client to trash',
        'audit.permanentDeletedClient': 'Permanently deleted client',
        'audit.permanentDeletedInvoice': 'Permanently deleted invoice',
        'audit.permanentDeletedPayment': 'Permanently deleted payment of',
        'audit.movedPaymentToTrash': 'Moved payment of',
        'audit.movedInvoiceToTrash': 'Moved invoice to trash',
    },
    fa: {
        // Navigation
        'nav.dashboard': '\u062f\u0627\u0634\u0628\u0648\u0631\u062f',
        'nav.invoices': '\u0641\u0627\u06a9\u062a\u0648\u0631\u0647\u0627',
        'nav.clients': '\u0645\u0634\u062a\u0631\u06cc\u0627\u0646',
        'nav.products': '\u0645\u062d\u0635\u0648\u0644\u0627\u062a',
        'nav.payments': '\u067e\u0631\u062f\u0627\u062e\u062a\u200c\u0647\u0627',
        'nav.expenses': '\u0647\u0632\u06cc\u0646\u0647\u200c\u0647\u0627',
        'nav.reports': '\u06af\u0632\u0627\u0631\u0634\u200c\u0647\u0627',
        'nav.settings': '\u062a\u0646\u0638\u06cc\u0645\u0627\u062a',
        'nav.backup': '\u067e\u0634\u062a\u06cc\u0628\u0627\u0646\u200c\u06af\u06cc\u0631\u06cc',
        'nav.conflicts': '\u062a\u0639\u0627\u0631\u0636\u0627\u062a',
        'nav.users': '\u06a9\u0627\u0631\u0628\u0631\u0627\u0646',
        'nav.trash': '\u0633\u0637\u0644 \u0632\u0628\u0627\u0644\u0647',

        // Common
        'common.save': '\u0630\u062e\u06cc\u0631\u0647',
        'common.cancel': '\u0644\u063a\u0648',
        'common.delete': '\u062d\u0630\u0641',
        'common.edit': '\u0648\u06cc\u0631\u0627\u06cc\u0634',
        'common.add': '\u0627\u0641\u0632\u0648\u062f\u0646',
        'common.create': '\u0627\u06cc\u062c\u0627\u062f',
        'common.search': '\u062c\u0633\u062a\u062c\u0648',
        'common.searchPlaceholder': '\u062c\u0633\u062a\u062c\u0648...',
        'common.filter': '\u0641\u06cc\u0644\u062a\u0631',
        'common.export': '\u062e\u0631\u0648\u062c\u06cc',
        'common.import': '\u0648\u0631\u0648\u062f\u06cc',
        'common.actions': '\u0639\u0645\u0644\u06cc\u0627\u062a',
        'common.status': '\u0648\u0636\u0639\u06cc\u062a',
        'common.date': '\u062a\u0627\u0631\u06cc\u062e',
        'common.amount': '\u0645\u0628\u0644\u063a',
        'common.total': '\u0645\u062c\u0645\u0648\u0639',
        'common.name': '\u0646\u0627\u0645',
        'common.email': '\u0627\u06cc\u0645\u06cc\u0644',
        'common.phone': '\u062a\u0644\u0641\u0646',
        'common.address': '\u0622\u062f\u0631\u0633',
        'common.notes': '\u06cc\u0627\u062f\u062f\u0627\u0634\u062a',
        'common.description': '\u062a\u0648\u0636\u06cc\u062d\u0627\u062a',
        'common.loading': '\u062f\u0631 \u062d\u0627\u0644 \u0628\u0627\u0631\u06af\u0630\u0627\u0631\u06cc...',
        'common.loadingApp': 'در حال بارگذاری مدیریت فاکتور...',
        'common.profileError': 'خطایی در بارگذاری پروفایل شما رخ داد.',
        'common.retry': 'تلاش مجدد',
        'common.noData': '\u062f\u0627\u062f\u0647\u200c\u0627\u06cc \u06cc\u0627\u0641\u062a \u0646\u0634\u062f',
        'common.confirm': '\u062a\u0623\u06cc\u06cc\u062f',
        'common.confirmDelete': '\u062a\u0623\u06cc\u06cc\u062f \u062d\u0630\u0641\u061f',
        'common.clickToConfirm': 'برای تأیید کلیک کنید',
        'common.required': '\u0627\u0644\u0632\u0627\u0645\u06cc',
        'common.optional': '\u0627\u062e\u062a\u06cc\u0627\u0631\u06cc',
        'common.noTax': '\u0628\u062f\u0648\u0646 \u0645\u0627\u0644\u06cc\u0627\u062a',
        'common.trackStock': '\u0631\u062f\u06cc\u0627\u0628\u06cc \u0645\u0648\u062c\u0648\u062f\u06cc',
        'common.forProfitTracking': '\u0628\u0631\u0627\u06cc \u067e\u06cc\u06af\u06cc\u0631\u06cc \u0633\u0648\u062f',

        // Auth
        'auth.appName': 'مدیریت فاکتور',
        'auth.signInTitle': 'وارد حساب کاربری خود شوید',
        'auth.password': 'رمز عبور',
        'auth.forgotPassword': 'رمز عبور را فراموش کرده‌اید؟',
        'auth.signIn': 'ورود',
        'auth.signingIn': 'در حال ورود...',
        'auth.noAccount': 'حساب کاربری ندارید؟',
        'auth.createAccount': 'یکی بسازید',
        'auth.enterEmailFirst': 'لطفا ابتدا ایمیل خود را وارد کنید',
        'auth.createAccountTitle': 'ایجاد حساب کاربری',
        'auth.confirmPassword': 'تکرار رمز عبور',
        'auth.createAccountAction': 'ایجاد حساب',
        'auth.creatingAccount': 'در حال ایجاد حساب...',
        'auth.motherAccountInfo': 'با ثبت نام، شما به عنوان حساب مادر برای شرکت خود شناخته می‌شوید. می‌توانید پس از راه‌اندازی، کاربران زیرمجموعه را دعوت کنید.',
        'auth.alreadyHaveAccount': 'قبلاً حساب کاربری دارید؟',
        'auth.signInLink': 'وارد شوید',
        'auth.companyNamePlaceholder': 'شرکت من',
        'auth.emailPlaceholder': 'ایمیل@example.com',
        'auth.passwordPlaceholder': '••••••••',
        'auth.passwordsDoNotMatch': 'رمز عبور مطابقت ندارد',
        'auth.createAccountFailed': 'ایجاد حساب با شکست مواجه شد',
        'auth.companyNameRequired': 'نام شرکت الزامی است',
        'auth.passwordLength': 'رمز عبور باید حداقل ۶ کاراکتر باشد',
        'auth.confirmPasswordRequired': 'لطفا رمز عبور را تکرار کنید',

        // Dashboard
        'dashboard.title': 'داشبورد',
        'dashboard.subtitle': 'خوش آمدید! نمای کلی کسب و کار شما',
        'dashboard.revenueThisMonth': 'درآمد این ماه',
        'dashboard.lastMonth': 'ماه گذشته',
        'dashboard.outstanding': 'معوقات',
        'dashboard.overdue': 'سررسید گذشته',
        'dashboard.netProfit': 'سود خالص (سالانه)',
        'dashboard.revenueOverview': 'نمای درآمد',
        'dashboard.invoiceStatus': 'وضعیت فاکتورها',
        'dashboard.topClients': 'مشتریان برتر',
        'dashboard.recentActivity': 'فعالیت‌های اخیر',
        'dashboard.noDataYet': 'هنوز داده‌ای نیست',
        'dashboard.noRecentActivity': 'فعالیت اخیری نیست',

        // Invoices
        'invoices.title': 'فاکتورها',
        'invoices.subtitle': 'مدیریت فاکتورهای شما',
        'invoices.new': 'فاکتور جدید',
        'invoices.all': 'همه',
        'invoices.allStatus': 'همه وضعیت‌ها',
        'invoices.draft': 'پیش‌نویس',
        'invoices.sent': 'ارسال شده',
        'invoices.paid': 'پرداخت شده',
        'invoices.partial': 'پرداخت جزئی',
        'invoices.overdue': 'سررسید گذشته',
        'invoices.void': '\u0628\u0627\u0637\u0644',
        'invoices.dueDate': '\u062a\u0627\u0631\u06cc\u062e \u0633\u0631\u0631\u0633\u06cc\u062f',
        'invoices.viewEdit': '\u0645\u0634\u0627\u0647\u062f\u0647/\u0648\u06cc\u0631\u0627\u06cc\u0634',
        'invoices.exportPdf': 'خروجی PDF',
        'invoices.sendEmail': 'ارسال ایمیل',
        'invoices.duplicate': 'کپی',
        'invoices.markAsPaid': 'علامت‌گذاری پرداخت شده',

        // Clients
        'clients.title': 'مشتریان',
        'clients.subtitle': 'مدیریت مشتریان و مخاطبین',
        'clients.addClient': 'افزودن مشتری',
        'clients.editClient': 'ویرایش مشتری',
        'clients.billingAddress': 'آدرس صورتحساب',
        'clients.shippingAddress': 'آدرس ارسال',
        'clients.taxNumber': 'شماره مالیاتی',

        // Products
        'products.title': 'محصولات',
        'products.subtitle': 'مدیریت محصولات و خدمات',
        'products.addProduct': 'افزودن محصول',
        'products.editProduct': 'ویرایش محصول',
        'products.sku': 'کد محصول',
        'products.unit': 'واحد',
        'products.price': 'قیمت',
        'products.cost': 'هزینه',
        'products.stock': 'موجودی',
        'products.trackStock': 'ردیابی موجودی',

        // Product Units
        'units.pcs': 'عدد',
        'units.hour': 'ساعت',
        'units.hrs': 'ساعت',
        'units.day': 'روز',
        'units.days': 'روز',
        'units.service': 'سرویس',
        'units.kg': 'کیلوگرم',
        'units.m': 'متر',
        'units.units': 'واحد',
        'units.items': 'آیتم',

        // Payments
        'payments.title': '\u067e\u0631\u062f\u0627\u062e\u062a\u200c\u0647\u0627',
        'payments.subtitle': '\u067e\u06cc\u06af\u06cc\u0631\u06cc \u067e\u0631\u062f\u0627\u062e\u062a\u200c\u0647\u0627 \u0648 \u0628\u0627\u0632\u067e\u0631\u062f\u0627\u062e\u062a\u200c\u0647\u0627',
        'payments.recordPayment': '\u062b\u0628\u062a \u067e\u0631\u062f\u0627\u062e\u062a',
        'payments.payInFull': '\u067e\u0631\u062f\u0627\u062e\u062a \u06a9\u0627\u0645\u0644',
        'payments.method': '\u0631\u0648\u0634',
        'payments.reference': '\u0645\u0631\u062c\u0639',
        'payments.referencePlaceholder': '\u0634\u0645\u0627\u0631\u0647 \u062a\u0631\u0627\u06a9\u0646\u0634\u060c \u0634\u0645\u0627\u0631\u0647 \u0686\u06a9 \u0648 \u063a\u06cc\u0631\u0647',
        'payments.isRefund': '\u0627\u06cc\u0646 \u06cc\u06a9 \u0628\u0627\u0632\u067e\u0631\u062f\u0627\u062e\u062a \u0627\u0633\u062a',
        'payments.selectInvoice': '\u0627\u0646\u062a\u062e\u0627\u0628 \u0641\u0627\u06a9\u062a\u0648\u0631',
        'payments.savePayment': '\u0630\u062e\u06cc\u0631\u0647 \u067e\u0631\u062f\u0627\u062e\u062a',
        'payments.cash': '\u0646\u0642\u062f\u06cc',
        'payments.bankTransfer': '\u0627\u0646\u062a\u0642\u0627\u0644 \u0628\u0627\u0646\u06a9\u06cc',
        'payments.card': '\u06a9\u0627\u0631\u062a',
        'payments.check': '\u0686\u06a9',
        'payments.other': '\u0633\u0627\u06cc\u0631',
        'payments.due': '\u0628\u0627\u0642\u06cc\u0645\u0627\u0646\u062f\u0647',

        // Expenses
        'expenses.title': '\u0647\u0632\u06cc\u0646\u0647\u200c\u0647\u0627',
        'expenses.subtitle': '\u067e\u06cc\u06af\u06cc\u0631\u06cc \u0647\u0632\u06cc\u0646\u0647\u200c\u0647\u0627\u06cc \u06a9\u0633\u0628 \u0648 \u06a9\u0627\u0631',
        'expenses.addExpense': '\u0627\u0641\u0632\u0648\u062f\u0646 \u0647\u0632\u06cc\u0646\u0647',
        'expenses.editExpense': '\u0648\u06cc\u0631\u0627\u06cc\u0634 \u0647\u0632\u06cc\u0646\u0647',
        'expenses.category': '\u062f\u0633\u062a\u0647\u200c\u0628\u0646\u062f\u06cc',
        'expenses.vendor': '\u0641\u0631\u0648\u0634\u0646\u062f\u0647',

        // Reports
        'reports.title': 'گزارش‌ها',
        'reports.subtitle': 'تحلیل عملکرد کسب و کار',
        'reports.sales': 'فروش',
        'reports.tax': 'مالیات',
        'reports.profit': 'سود',
        'reports.exportCsv': 'خروجی CSV',
        'reports.exportPdf': 'خروجی PDF',

        // Expense Categories
        'expenses.cat.officeSupplies': 'لوازم اداری',
        'expenses.cat.travel': 'سفر',
        'expenses.cat.utilities': 'قبوض و خدمات',
        'expenses.cat.marketing': 'بازاریابی',
        'expenses.cat.other': 'سایر',

        // Settings
        'settings.title': 'تنظیمات',
        'settings.saveSuccess': 'تنظیمات با موفقیت ذخیره شد',
        'settings.confirmSave': 'تایید ذخیره',
        'settings.confirmSaveMessage': 'آیا مطمئن هستید که می‌خواهید این تغییرات را ذخیره کنید؟',
        'settings.subtitle': 'پیکربندی ترجیحات کسب و کار',
        'settings.companyInfo': 'اطلاعات شرکت',

        // Tutorial
        'tutorial.welcome.title': 'به مدیریت فاکتور خوش آمدید',
        'tutorial.welcome.desc': 'بیایید یک تور سریع برای شروع کار شما داشته باشیم.',
        'tutorial.dashboard.title': 'داشبورد',
        'tutorial.dashboard.desc': 'نمای کلی کسب و کار، نمودارهای درآمد و فعالیت‌های اخیر خود را مشاهده کنید.',
        'tutorial.invoices.title': 'فاکتورها',
        'tutorial.invoices.desc': 'فاکتورهای مشتریان خود را ایجاد، مدیریت و چاپ کنید.',
        'tutorial.clients.title': 'مشتریان',
        'tutorial.clients.desc': 'پایگاه داده مشتریان خود را مدیریت کنید و تاریخچه آنها را مشاهده کنید.',
        'tutorial.products.title': 'محصولات',
        'tutorial.products.desc': 'موجودی، خدمات و قیمت‌های خود را پیگیری کنید.',
        'tutorial.payments.title': 'پرداخت‌ها',
        'tutorial.payments.desc': 'پرداخت‌ها را ثبت کنید و مانده‌های معوق را پیگیری کنید.',
        'tutorial.expenses.title': 'هزینه‌ها',
        'tutorial.expenses.desc': 'هزینه‌های تجاری را ثبت و دسته‌بندی کنید.',
        'tutorial.reports.title': 'گزارش‌ها',
        'tutorial.reports.desc': 'گزارش‌های مالی و تحلیلی دقیق را مشاهده کنید.',
        'tutorial.settings.title': 'تنظیمات',
        'tutorial.settings.desc': 'جزئیات شرکت، لوگو و نرخ‌های مالیاتی خود را پیکربندی کنید.',
        'tutorial.backup.title': 'پشتیبان‌گیری',
        'tutorial.backup.desc': 'با ایجاد و بازیابی نسخه‌های پشتیبان، از داده‌های خود محافظت کنید.',
        'tutorial.trash.title': 'سطل زباله',
        'tutorial.trash.desc': 'موارد حذف شده را بازیابی یا به طور دائمی حذف کنید.',
        'tutorial.conflicts.title': 'تعارضات همگام‌سازی',
        'tutorial.conflicts.desc': 'تعارضات داده بین ذخیره‌سازی محلی و ابری را حل کنید.',
        'tutorial.users.title': 'مدیریت کاربران',
        'tutorial.users.desc': 'اعضای تیم را دعوت و مدیریت کنید.',
        'tutorial.sync.title': 'همگام‌سازی ابری',
        'tutorial.sync.desc': 'داده‌های خود را در تمام دستگاه‌ها همگام نگه دارید.',
        'tutorial.next': 'بعدی',

        'tutorial.prev': 'قبلی',
        'tutorial.done': 'پایان',
        'settings.restartTutorial': 'شروع مجدد تور آموزشی',
        'settings.companyName': 'نام شرکت',
        'settings.companyLogo': 'لوگوی شرکت',
        'settings.noLogo': 'بدون لوگو',
        'settings.chooseLogo': 'انتخاب لوگو',
        'settings.companyAddress': 'آدرس',
        'settings.companyEmail': 'ایمیل',
        'settings.companyPhone': 'تلفن',
        'settings.taxId': 'شماره مالیاتی',
        'settings.taxIdHint': 'شماره مالیات بر ارزش افزوده',
        'settings.invoiceSettings': 'تنظیمات فاکتور',
        'settings.invoicePrefix': 'پیشوند فاکتور',
        'settings.nextNumber': 'شماره بعدی',
        'settings.currency': 'واحد پول',
        'settings.currencySymbol': 'نماد ارز',
        'settings.pdfTemplate': 'قالب PDF',
        'settings.paperSize': 'اندازه کاغذ',
        'settings.defaultTerms': 'شرایط پیش‌فرض',
        'settings.termsPlaceholder': 'شرایط پرداخت...',
        'settings.defaultNotes': 'یادداشت پیش‌فرض',
        'settings.notesPlaceholder': 'پیام تشکر...',
        'settings.footerText': 'متن پایین صفحه',
        'settings.footerPlaceholder': 'متن پایین فاکتور',
        'settings.taxRates': 'نرخ‌های مالیات',
        'settings.taxName': 'نام مالیات',
        'settings.security': 'امنیت',
        'settings.autoLock': 'قفل خودکار بعد از (دقیقه)',
        'settings.autoLockHint': 'برای غیرفعال کردن ۰ بگذارید',
        'settings.appearance': 'ظاهر',
        'settings.theme': 'پوسته',
        'settings.language': 'زبان',
        'settings.dark': 'تیره',
        'settings.light': 'روشن',
        'settings.system': 'سیستم',
        'settings.saveSettings': 'ذخیره تنظیمات',
        'settings.saving': 'در حال ذخیره...',

        // Table Headers
        'table.name': 'نام',
        'table.email': 'ایمیل',
        'table.phone': 'تلفن',
        'table.address': 'آدرس',
        'table.actions': 'عملیات',
        'table.date': 'تاریخ',
        'table.invoice': 'فاکتور',
        'table.client': 'مشتری',
        'table.amount': 'مبلغ',
        'table.status': 'وضعیت',
        'table.method': 'روش',
        'table.type': 'نوع',
        'table.category': 'دسته‌بندی',
        'table.vendor': 'فروشنده',
        'table.description': 'توضیحات',
        'table.sku': 'کد محصول',
        'table.unit': 'واحد',
        'table.price': 'قیمت',
        'table.stock': 'موجودی',
        'table.paid': 'پرداخت شده',
        'table.total': 'مجموع',
        'table.balance': 'مانده',
        'table.taxRate': 'نرخ مالیات',
        'table.baseAmount': 'مبلغ پایه',
        'table.taxCollected': 'مالیات جمع‌آوری شده',

        // Reports Specific
        'reports.from': 'از:',
        'reports.to': 'تا:',
        'reports.invoicesCount': 'فاکتورها',
        'reports.totalBilled': 'کل صورتحساب',
        'reports.collected': 'دریافت شده',
        'reports.taxTotal': 'مالیات',
        'reports.taxableAmount': 'مبلغ مشمول مالیات',
        'reports.taxCollected': 'مالیات جمع‌آوری شده',
        'reports.revenue': 'درآمد',
        'reports.cogs': 'بهای تمام شده',
        'reports.grossProfit': 'سود ناخالص',
        'reports.netProfit': 'سود خالص',
        'reports.expensesCount': 'هزینه‌ها',
        'reports.totalSpent': 'کل هزینه',
        'reports.byCategory': 'بر اساس دسته‌بندی',
        'reports.transactions': 'تراکنش‌ها',
        'reports.received': 'دریافت شده',
        'reports.refunded': 'بازپرداخت شده',

        // Empty States
        'empty.noInvoices': 'هنوز فاکتوری نیست',
        'empty.createFirstInvoice': 'اولین فاکتور خود را ایجاد کنید',
        'empty.noClients': 'هنوز مشتری نیست',
        'empty.addFirstClient': 'اولین مشتری خود را اضافه کنید',
        'empty.noProducts': 'هنوز محصولی نیست',
        'empty.addFirstProduct': 'اولین محصول خود را اضافه کنید',
        'empty.noPayments': 'هنوز پرداختی نیست',
        'empty.recordFirstPayment': 'اولین پرداخت خود را ثبت کنید',
        'empty.noExpenses': 'هنوز هزینه‌ای نیست',
        'empty.addFirstExpense': 'پیگیری هزینه‌ها را شروع کنید',

        // Trash
        'trash.title': 'سطل زباله',
        'trash.subtitle': 'موارد حذف شده قابل بازیابی یا حذف دائمی هستند',
        'trash.empty': 'سطل زباله خالی است',
        'trash.emptyDesc': 'هیچ مورد حذف شده‌ای در این دسته وجود ندارد',
        'trash.deletedAt': 'تاریخ حذف',
        'trash.warning': 'هشدار',
        'trash.warningDesc': 'موارد حذف شده به صورت دائمی قابل بازیابی نیستند. موارد بازیابی شده به مکان اصلی خود باز می‌گردند.',
        'trash.restore': 'بازیابی',
        'trash.permanentDelete': 'حذف دائمی',
        'trash.confirm': 'تایید',
        'trash.cancel': 'لغو',

        // Status Labels
        'status.paid': 'پرداخت شده',
        'status.unpaid': 'پرداخت نشده',
        'status.overdue': 'سررسید گذشته',
        'status.draft': 'پیش‌نویس',
        'status.sent': 'ارسال شده',
        'status.void': 'باطل',
        'status.payment': 'پرداخت',
        'status.refund': 'بازپرداخت',

        // Activity Messages
        'activity.createdInvoice': 'فاکتور ایجاد شد',
        'activity.deletedInvoice': 'فاکتور حذف شد',
        'activity.updatedInvoice': 'فاکتور بروزرسانی شد',
        'activity.createdClient': 'مشتری ایجاد شد',
        'activity.createdProduct': 'محصول ایجاد شد',
        'activity.paymentFor': 'پرداخت {amount} برای فاکتور {invoice}',

        // Backup
        'backup.title': '\u067e\u0634\u062a\u06cc\u0628\u0627\u0646\u200c\u06af\u06cc\u0631\u06cc \u0648 \u062f\u0627\u062f\u0647',
        'backup.subtitle': '\u067e\u0634\u062a\u06cc\u0628\u0627\u0646\u200c\u06af\u06cc\u0631\u06cc\u060c \u0628\u0627\u0632\u06cc\u0627\u0628\u06cc \u0648 \u0645\u062f\u06cc\u0631\u06cc\u062a \u062f\u0627\u062f\u0647\u200c\u0647\u0627',
        'backup.backupRestore': '\u067e\u0634\u062a\u06cc\u0628\u0627\u0646\u200c\u06af\u06cc\u0631\u06cc \u0648 \u0628\u0627\u0632\u06cc\u0627\u0628\u06cc',
        'backup.backupDesc': '\u067e\u0634\u062a\u06cc\u0628\u0627\u0646 \u0631\u0645\u0632\u06af\u0630\u0627\u0631\u06cc \u0634\u062f\u0647 \u0627\u0632 \u062a\u0645\u0627\u0645 \u062f\u0627\u062f\u0647\u200c\u0647\u0627\u06cc \u0634\u0645\u0627 \u0634\u0627\u0645\u0644 \u0641\u0627\u06a9\u062a\u0648\u0631\u0647\u0627\u060c \u0645\u0634\u062a\u0631\u06cc\u0627\u0646\u060c \u0645\u062d\u0635\u0648\u0644\u0627\u062a\u060c \u067e\u0631\u062f\u0627\u062e\u062a\u200c\u0647\u0627 \u0648 \u062a\u0646\u0638\u06cc\u0645\u0627\u062a \u0627\u06cc\u062c\u0627\u062f \u06a9\u0646\u06cc\u062f.',
        'backup.encryptionPassword': '\u0631\u0645\u0632 \u0639\u0628\u0648\u0631 \u0631\u0645\u0632\u06af\u0630\u0627\u0631\u06cc (\u0627\u062e\u062a\u06cc\u0627\u0631\u06cc)',
        'backup.createBackup': '\u0627\u06cc\u062c\u0627\u062f \u067e\u0634\u062a\u06cc\u0628\u0627\u0646',
        'backup.restoreBackup': '\u0628\u0627\u0632\u06cc\u0627\u0628\u06cc \u067e\u0634\u062a\u06cc\u0628\u0627\u0646',
        'backup.importData': '\u0648\u0627\u0631\u062f \u06a9\u0631\u062f\u0646 \u062f\u0627\u062f\u0647',
        'backup.importDesc': '\u0645\u0634\u062a\u0631\u06cc\u0627\u0646 \u0648 \u0645\u062d\u0635\u0648\u0644\u0627\u062a \u0631\u0627 \u0627\u0632 \u0641\u0627\u06cc\u0644\u200c\u0647\u0627\u06cc CSV \u0648\u0627\u0631\u062f \u06a9\u0646\u06cc\u062f. \u0641\u0631\u0645\u062a \u0645\u0648\u0631\u062f \u0627\u0646\u062a\u0638\u0627\u0631 \u0628\u0631\u0627\u06cc \u0645\u0634\u062a\u0631\u06cc\u0627\u0646: \u0646\u0627\u0645\u060c \u0627\u06cc\u0645\u06cc\u0644\u060c \u062a\u0644\u0641\u0646\u060c \u0622\u062f\u0631\u0633. \u0628\u0631\u0627\u06cc \u0645\u062d\u0635\u0648\u0644\u0627\u062a: \u06a9\u062f\u060c \u0646\u0627\u0645\u060c \u0648\u0627\u062d\u062f\u060c \u0642\u06cc\u0645\u062a\u060c \u0647\u0632\u06cc\u0646\u0647.',
        'backup.importClients': '\u0648\u0627\u0631\u062f \u06a9\u0631\u062f\u0646 \u0645\u0634\u062a\u0631\u06cc\u0627\u0646',
        'backup.importProducts': '\u0648\u0627\u0631\u062f \u06a9\u0631\u062f\u0646 \u0645\u062d\u0635\u0648\u0644\u0627\u062a',
        'backup.exportData': '\u062e\u0631\u0648\u062c\u06cc \u062f\u0627\u062f\u0647',
        'backup.exportDesc': '\u062f\u0627\u062f\u0647\u200c\u0647\u0627\u06cc \u062e\u0648\u062f \u0631\u0627 \u0628\u0647 \u0635\u0648\u0631\u062a \u0641\u0627\u06cc\u0644 CSV \u0628\u0631\u0627\u06cc \u0627\u0633\u062a\u0641\u0627\u062f\u0647 \u062f\u0631 \u0635\u0641\u062d\u0647 \u06af\u0633\u062a\u0631\u062f\u0647 \u06cc\u0627 \u0628\u0631\u0646\u0627\u0645\u0647\u200c\u0647\u0627\u06cc \u062f\u06cc\u06af\u0631 \u062e\u0631\u0648\u062c\u06cc \u0628\u06af\u06cc\u0631\u06cc\u062f.',
        'backup.databaseLocation': '\u0645\u062d\u0644 \u067e\u0627\u06cc\u06af\u0627\u0647 \u062f\u0627\u062f\u0647',
        'backup.databaseDesc': '\u062f\u0627\u062f\u0647\u200c\u0647\u0627\u06cc \u0634\u0645\u0627 \u0628\u0647 \u0635\u0648\u0631\u062a \u0645\u062d\u0644\u06cc \u0630\u062e\u06cc\u0631\u0647 \u0634\u062f\u0647 \u062f\u0631:',

        // Form Fields
        'form.billingAddress': '\u0622\u062f\u0631\u0633 \u0635\u0648\u0631\u062a\u062d\u0633\u0627\u0628',
        'form.shippingAddress': '\u0622\u062f\u0631\u0633 \u0627\u0631\u0633\u0627\u0644',
        'form.taxNumber': '\u0634\u0645\u0627\u0631\u0647 \u0645\u0627\u0644\u06cc\u0627\u062a\u06cc',
        'form.category': '\u062f\u0633\u062a\u0647\u200c\u0628\u0646\u062f\u06cc',
        'form.vendor': '\u0641\u0631\u0648\u0634\u0646\u062f\u0647',
        'form.vendorPlaceholder': '\u0646\u0627\u0645 \u0641\u0631\u0648\u0634\u0646\u062f\u0647',
        'form.whatExpenseFor': '\u0627\u06cc\u0646 \u0647\u0632\u06cc\u0646\u0647 \u0628\u0631\u0627\u06cc \u0686\u0647 \u0628\u0648\u062f\u061f',
        'form.tax': '\u0645\u0627\u0644\u06cc\u0627\u062a',
        'form.update': '\u0628\u0631\u0648\u0632\u0631\u0633\u0627\u0646\u06cc',

        // Messages
        'msg.saved': '\u0628\u0627 \u0645\u0648\u0641\u0642\u06cc\u062a \u0630\u062e\u06cc\u0631\u0647 \u0634\u062f',
        'msg.deleted': '\u0628\u0627 \u0645\u0648\u0641\u0642\u06cc\u062a \u062d\u0630\u0641 \u0634\u062f',
        'msg.created': '\u0628\u0627 \u0645\u0648\u0641\u0642\u06cc\u062a \u0627\u06cc\u062c\u0627\u062f \u0634\u062f',
        'msg.updated': '\u0628\u0627 \u0645\u0648\u0641\u0642\u06cc\u062a \u0628\u0631\u0648\u0632\u0631\u0633\u0627\u0646\u06cc \u0634\u062f',
        'msg.error': '\u062e\u0637\u0627\u06cc\u06cc \u0631\u062e \u062f\u0627\u062f',

        // Cloud Sync
        'sync.title': 'همگام\u200cسازی ابری',
        'sync.allSynced': '\u0647\u0645\u0647 \u062f\u0627\u062f\u0647\u200c\u0647\u0627 \u0647\u0645\u06af\u0627\u0645 \u0634\u062f',
        'sync.changesPending': '\u062a\u063a\u06cc\u06cc\u0631\u0627\u062a \u062f\u0631 \u0627\u0646\u062a\u0638\u0627\u0631 \u0647\u0645\u06af\u0627\u0645\u200c\u0633\u0627\u0632\u06cc',
        'sync.syncing': '\u062f\u0631 \u062d\u0627\u0644 \u0647\u0645\u06af\u0627\u0645\u200c\u0633\u0627\u0632\u06cc...',
        'sync.neverSynced': '\u0647\u0631\u06af\u0632 \u0647\u0645\u06af\u0627\u0645 \u0646\u0634\u062f\u0647',
        'sync.syncNow': 'همگام\u200cسازی اکنون',
        'sync.autoSync': 'همگام\u200cسازی خودکار',
        'sync.autoSyncDescription': 'همگام\u200cسازی خودکار هر ۳۰ دقیقه',
        'sync.dataInfo': 'داده\u200cهای شما در Firebase همگام می\u200cشود و از هر دستگاهی قابل دسترسی است',
        'sync.reminderInfo': 'در صورت وجود تغییرات ذخیره نشده، قبل از بستن به شما یادآوری می\u200cشود',

        // Users Management
        'users.title': 'مدیریت کاربران',
        'users.subtitle': 'دعوت و مدیریت کاربران فرزند برای سازمان شما',
        'users.addUser': 'افزودن کاربر',
        'users.totalUsers': 'کل کاربران',
        'users.admins': 'مدیران',
        'users.childUsers': 'کاربران فرزند',
        'users.user': 'کاربر',
        'users.email': 'ایمیل',
        'users.role': 'نقش',
        'users.status': 'وضعیت',
        'users.actions': 'عملیات',
        'users.active': 'فعال',
        'users.admin': 'مدیر',
        'users.noUsers': 'هنوز کاربری وجود ندارد. روی "افزودن کاربر" کلیک کنید.',
        'users.createChildUser': 'ایجاد کاربر فرزند',
        'users.userNamePlaceholder': 'نام کاربر',
        'users.userPassword': 'رمز عبور کاربر',
        'users.minChars': 'حداقل ۶ کاراکتر',
        'users.adminPassword': 'رمز عبور شما (مدیر)',
        'users.adminPasswordPlaceholder': 'رمز عبور خود را برای تأیید وارد کنید',
        'users.reauthNote': 'برای احراز هویت مجدد پس از ایجاد کاربر لازم است',
        'users.addUserNote': 'این کاربر به سازمان شما اضافه می‌شود و می‌تواند به داده‌های مشترک دسترسی داشته باشد.',
        'users.creating': 'در حال ایجاد...',
        'users.createUser': 'ایجاد کاربر',

        // Conflicts
        'conflicts.title': 'تعارضات همگام\u200cساز',
        'conflicts.subtitle': 'بررسی و حل اختلافات بین داده\u200cهای محلی و ابری',
        'conflicts.checkConflicts': 'بررسی تعارضات',
        'conflicts.pending': 'تعارضات در انتظار',
        'conflicts.resolvedToday': 'حل شده امروز',
        'conflicts.entityTypes': 'انواع موجودیت',
        'conflicts.noConflicts': 'تعارضی یافت نشد',
        'conflicts.inSync': 'داده\u200cهای محلی و ابری شما همگام هستند!',
        'conflicts.checking': 'در حال بررسی تعارضات...',
        'conflicts.keepLocal': 'نگهداری نسخه محلی',
        'conflicts.keepRemote': 'نگهداری نسخه ابری',
        'conflicts.localVersion': 'نسخه محلی',
        'conflicts.remoteVersion': 'نسخه ابری',
        'conflicts.recentlyResolved': 'اخیراً حل شده',

        // Invoice Editor
        'invoice.new': 'فاکتور جدید',
        'invoice.save': 'ذخیره فاکتور',
        'invoice.client': 'مشتری',
        'invoice.newClient': 'مشتری جدید',
        'invoice.selectClient': 'انتخاب مشتری',
        'invoice.items': 'اقلام',
        'invoice.addItem': 'افزودن قلم',
        'invoice.description': 'توضیحات',
        'invoice.quickSelect': 'انتخاب سریع محصول...',
        'invoice.itemDescription': 'توضیحات قلم *',
        'invoice.qty': 'تعداد',
        'invoice.unitPrice': 'قیمت واحد',
        'invoice.taxPercent': 'مالیات %',
        'invoice.discPercent': 'تخفیف %',
        'invoice.total': 'جمع',
        'invoice.notes': 'یادداشت\u200cها',
        'invoice.additionalNotes': 'یادداشت\u200cهای اضافی...',
        'invoice.terms': 'شرایط',
        'invoice.termsConditions': 'شرایط و ضوابط...',
        'invoice.issueDate': 'تاریخ صدور',
        'invoice.dueDate': 'تاریخ سررسید',
        'invoice.summary': 'خلاصه',
        'invoice.subtotal': 'جمع جزء',
        'invoice.tax': 'مالیات',

        // Audit Messages
        'audit.restoredClient': 'بازیابی مشتری',
        'audit.restoredProduct': 'بازیابی محصول',
        'audit.restoredInvoice': 'بازیابی فاکتور',
        'audit.movedClientToTrash': 'انتقال مشتری به سطل زباله',
        'audit.movedProductToTrash': 'انتقال محصول به سطل زباله',
        'audit.permanentDeletedClient': 'حذف دائمی مشتری',
        'audit.permanentDeletedProduct': 'حذف دائمی محصول',
        'audit.permanentDeletedInvoice': 'حذف دائمی فاکتور',
        'audit.permanentDeletedPayment': 'حذف دائمی پرداخت به مبلغ',
        'audit.movedPaymentToTrash': 'انتقال پرداخت به مبلغ',
        'audit.movedInvoiceToTrash': 'انتقال فاکتور به سطل زباله',
    },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('language') as Language;
        return saved || 'en';
    });

    const isRTL = language === 'fa';

    useEffect(() => {
        document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language, isRTL]);

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    return (
        <LanguageContext.Provider value={{ language, t, setLanguage, isRTL }}>
            {children}
        </LanguageContext.Provider>
    );
}
